apiVersion: v1
kind: Service
metadata:
  namespace: pdns
  name: haproxy-pdns-service
  labels:
    app: haproxy-pdns
    tier: frontend
spec:
  type: NodePort
  selector:
    app: haproxy-pdns
    tier: frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8008
    nodePort: 30002
  - name: stats
    protocol: TCP
    port: 7000
    targetPort: 7000
    nodePort: 30005