apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
  namespace: pdns
  labels:
    app: haproxy
data:
  haproxy.cfg: |
    global
        log 127.0.0.1 local0
        maxconn 100

    defaults
        log global
        mode tcp
        retries 3
        timeout client 30m
        timeout connect 4s
        timeout server 30m
        timeout check 5s

    listen stats
        mode http
        bind *:80
        stats enable
        stats uri /

    listen postgres
        bind *:5000
        option httpchk
        http-check expect status 200
        default-server inter 3s fall 3 rise 2 on-marked-down shutdown-sessions
        server pgsql-01 10.0.4.71:5432 maxconn 100 check port 8008
        server pgsql-02 10.0.4.72:5432 maxconn 100 check port 8008
        server pgsql-03 10.0.4.73:5432 maxconn 100 check port 8008
  #haproxy.cfg: |