---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: haproxy-vol
  labels:
    app: harpoxy
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "nfs-csi"
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  mountOptions:
    - nfsvers=4
    - hard
  nfs:
    server: 10.0.4.55
    path: "/home/dmitriy/data/haproxy-pdns/"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: pdns
  name: harpoxy-log-claim
  labels:
    app: harpoxy
spec:
  storageClassName: "nfs-csi"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
