apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pdns 
  name: haproxy-pdns
  labels:
    app: haproxy-pdns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy-pdns
      tier: frontend
  template:
    metadata:
      labels:
        app: haproxy-pdns
        tier: frontend
    spec:
      containers:
      - name: haproxy-pdns
        image: haproxy:2.8-alpine
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
            - name: http
              protocol: TCP 
              containerPort: 80
            - name: stats
              protocol: TCP 
              containerPort: 7000
        volumeMounts:
            - mountPath: "/usr/local/etc/haproxy/"
              name: haproxy-cfg
              readOnly: true
        command: ["sh"]
        args: ["-c", "haproxy -f /usr/local/etc/haproxy/haproxy.cfg"]
      volumes:
          - name: haproxy-cfg
            configMap:
              name: haproxy-config