apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-pdns-config
  namespace: pdns
  labels:
    app: haproxy-pdns
data:
  haproxy.cfg: |
    global
        log /dev/log local0
        maxconn 100
        stats timeout 30s

    defaults
        log global
        mode http
        retries 3
        option httplog
        timeout client 30m
        timeout connect 4s
        timeout server 30m
        timeout check 5s

    listen stats
        mode http
        bind *:7000
        stats enable
        stats refresh 5s
        stats uri /
        stats auth status:status

    listen power_admin
        mode http
        bind *:80
        balance roundrobin
        stats enable
        option httpchk
        http-check expect status 200
        server pdns-01 10.0.4.103:80 maxconn 100 send-proxy check inter 2000 fall 3
        server pdns-02 10.0.4.104:80 maxconn 100 send-proxy check inter 2000 fall 3
