apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: haproxy-pgs-hpa
  namespace: pdns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: haproxy-pgs
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
