apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-pdns-config
  namespace: pdns
  labels:
    app: haproxy-pdns
data:
  haproxy.cfg: |
    global
        log /dev/log local0
        maxconn 100
        chroot /var/lib/haproxy
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

    defaults
        log global
        mode http
        retries 3
        option httplog
        timeout client 30m
        timeout connect 4s
        timeout server 30m
        timeout check 5s

    listen stats
        mode http
        bind *:5000
        stats enable
        stats show-legends
        stats refresh 5s
        stats uri /
        stats auth status:status

    frontend https-in
        log /dev/log local0
        mode http
        bind *:80
        default_backend pdns-server


    backend pdns-server
        balance roundrobin
        option httpchk
        server pdns-01 10.0.4.103:80 maxconn 100 check send-proxy
        server pdns-02 10.0.4.104:80 maxconn 100 check send-proxy
        server pdns-03 10.0.4.105:80 maxconn 100 check send-proxy